# Generated by Django 3.2.9 on 2021-11-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
